/**
 * Reporter: writes the run summary and, unless this is a dry run, opens the
 * pull request.
 *
 * Deterministic, like the Executor and the static checks — every input it
 * needs (plan, generation, execution, healing, review) is already
 * structured JSON by the time this runs, so templating a summary from it
 * needs no reasoning an LLM call would add latency and cost for.
 *
 * Never pushes to `main`: it always creates a new branch first, and if
 * there is no `origin` remote or the caller passed `dryRun`, it stops after
 * writing `summary.md` and never touches git at all.
 */
import { config } from '../core/config.js';
import * as git from '../core/git.js';
import { createPullRequest } from '../core/github.js';
import type { RunContext } from '../core/run.js';
import type {
  ExecutionResult,
  ExplorationResult,
  GenerationResult,
  HealingResult,
  ReviewResult,
  TestPlan,
} from './types.js';

export interface ReporterOptions {
  run: RunContext;
  feature: string;
  targetUrl: string;
  provider: string;
  exploration: ExplorationResult;
  plan: TestPlan;
  generations: GenerationResult[];
  executions: ExecutionResult[];
  healings: HealingResult[];
  reviews: ReviewResult[];
  dryRun: boolean;
  baseBranch?: string;
  /** The Jira ticket this run was generated from, if any — embedded in the branch name and PR body. */
  jiraTicket?: { key: string; url: string };
}

export interface ReportResult {
  summaryPath: string;
  branch?: string;
  pullRequestUrl?: string;
}

export async function runReporter(options: ReporterOptions): Promise<ReportResult> {
  const { run, dryRun } = options;

  const { usage, estimatedUsd } = run.totals();
  const finalExecution = options.executions.at(-1);
  const finalReview = options.reviews.at(-1);
  const suspectedAppBugs = options.healings.flatMap((h) =>
    h.verdicts.filter((v) => v.verdict === 'suspected_app_bug')
  );

  const markdown = renderSummary({
    ...options,
    usage,
    estimatedUsd,
    finalExecution,
    finalReview,
    suspectedAppBugs,
  });
  run.saveText('summary.md', markdown);
  const summaryPath = `${run.dir}/summary.md`;

  const writtenPaths = [
    ...new Set(options.generations.flatMap((g) => g.filesWritten.map((f) => f.path))),
  ];

  if (dryRun) {
    run.log.info('Dry run: skipping branch creation, commit, and pull request.');
    return { summaryPath };
  }

  if (!(await git.hasRemote())) {
    run.log.warn(
      'No git remote "origin" configured — cannot open a pull request. Treating as dry run.'
    );
    return { summaryPath };
  }

  if (writtenPaths.length === 0) {
    run.log.warn('Nothing was written — skipping branch creation and pull request.');
    return { summaryPath };
  }

  const baseBranch = options.baseBranch ?? config.github.baseBranch;
  const branchSlug = options.jiraTicket
    ? slugify(options.jiraTicket.key)
    : slugify(options.feature);
  const branch = `testpilot/${branchSlug}-${Date.now().toString(36)}`;

  await git.createBranch(branch);
  await git.stagePaths(writtenPaths.map((p) => `framework/${p}`));

  if (!(await git.hasStagedChanges())) {
    run.log.warn(
      'Generated files match what is already committed — nothing to open a pull request for.'
    );
    await git.checkoutBranch(baseBranch);
    return { summaryPath, branch };
  }

  const titleSuffix = options.jiraTicket ? ` (${options.jiraTicket.key})` : '';

  await git.commit(
    `test: add generated coverage for "${options.feature}"${titleSuffix}\n\n` +
      `Generated by TestPilot_AI. See ${summaryPath} for the full run summary.`
  );
  await git.push(branch);

  if (config.github.token === undefined) {
    run.log.warn('GITHUB_TOKEN is not set — branch pushed, but no pull request was opened.');
    return { summaryPath, branch };
  }

  const pr = await createPullRequest({
    token: config.github.token,
    repo: config.github.repo,
    title: `test: add generated coverage for "${options.feature}"${titleSuffix}`,
    body: markdown,
    head: branch,
    base: baseBranch,
  });

  run.saveJson('pull-request.json', pr);
  return { summaryPath, branch, pullRequestUrl: pr.url };
}

function renderSummary(data: {
  feature: string;
  targetUrl: string;
  provider: string;
  plan: TestPlan;
  generations: GenerationResult[];
  finalExecution: ExecutionResult | undefined;
  finalReview: ReviewResult | undefined;
  healings: HealingResult[];
  suspectedAppBugs: { test: string; explanation: string }[];
  usage: { promptTokens: number; completionTokens: number; totalTokens: number };
  estimatedUsd: number;
  jiraTicket?: { key: string; url: string };
}): string {
  const lines: string[] = [
    `# TestPilot_AI run summary: ${data.feature}`,
    '',
    `Target: ${data.targetUrl}  •  Provider: ${data.provider}`,
    ...(data.jiraTicket ? [`Jira: ${data.jiraTicket.key} (${data.jiraTicket.url})`] : []),
    '',
    '## Plan',
    data.plan.summary,
    `${String(data.plan.cases.length)} case(s) planned: ` +
      data.plan.cases.map((c) => c.id).join(', '),
    '',
    '## Generated',
  ];

  const allFiles = data.generations.flatMap((g) => g.filesWritten);
  if (allFiles.length === 0) {
    lines.push('No files were generated.');
  } else {
    for (const file of allFiles) lines.push(`- \`${file.path}\` — ${file.reason}`);
  }
  lines.push('');

  lines.push('## Test run');
  if (data.finalExecution) {
    lines.push(
      `${String(data.finalExecution.passed)} passed, ${String(data.finalExecution.failed)} failed, ` +
        `${String(data.finalExecution.skipped)} skipped (final attempt).`
    );
  } else {
    lines.push('No execution was recorded.');
  }
  lines.push('');

  lines.push('## Healing');
  const fixed = data.healings.flatMap((h) => h.verdicts.filter((v) => v.verdict === 'fixed'));
  if (data.healings.length === 0) {
    lines.push('No healing was needed.');
  } else {
    lines.push(
      `${String(fixed.length)} test bug(s) fixed across ${String(data.healings.length)} attempt(s).`
    );
  }
  lines.push('');

  lines.push('## Suspected application bugs');
  if (data.suspectedAppBugs.length === 0) {
    lines.push('None.');
  } else {
    lines.push(
      '**These were not hidden by weakening an assertion — they are reported as likely real defects:**',
      ''
    );
    for (const bug of data.suspectedAppBugs) lines.push(`- **${bug.test}** — ${bug.explanation}`);
  }
  lines.push('');

  lines.push('## Review');
  if (data.finalReview) {
    lines.push(
      `Verdict: **${data.finalReview.verdict}** (round ${String(data.finalReview.round)}). ` +
        `Lint ${data.finalReview.lintPassed ? 'passed' : 'FAILED'}, ` +
        `type-check ${data.finalReview.typecheckPassed ? 'passed' : 'FAILED'}.`
    );
    const blocking = data.finalReview.findings.filter((f) => f.severity === 'blocking');
    if (blocking.length > 0) {
      lines.push('', 'Blocking findings:');
      for (const finding of blocking) lines.push(`- \`${finding.file}\`: ${finding.issue}`);
    }
  } else {
    lines.push('No review was recorded.');
  }
  lines.push('');

  lines.push('## Cost');
  lines.push(
    `${String(data.usage.totalTokens)} tokens ` +
      `(${String(data.usage.promptTokens)} prompt + ${String(data.usage.completionTokens)} completion) ` +
      `≈ $${data.estimatedUsd.toFixed(4)}.`
  );

  return lines.join('\n');
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 50);
}
